import {NavBar} from "@/components/atoms/nav-bar/NavBar";
import Head from "next/head";
import {Slider} from "@/components/molecules/slider/Slider";
import {MainCollections} from "@/components/molecules/main-collections/MainCollections";
import {CardFilm} from "@/components/atoms/card-film/CardFilm";
import {CardFilmList} from "@/components/molecules/card-film-list/CardFilmList";


export default function Home() {
  return (
    <>
      <Head>
        <title>Disney Plus Clone</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>


        {/* <link rel="shortcut icon"
              href="https://static-assets.bamgrid.com/product/disneyplus/favicons/favicon-aurora.9c40657cf520f9cfcf49dbb4f316aa7c.ico"/>*/}
      </Head>
      <div className="main-container">

        <header className="header">
          <NavBar/>

          <section>
            <Slider></Slider>
          </section>
        </header>

        <main className="main">
          <section>
            <MainCollections/>
          </section>
          <section>
            <CardFilmList titleCard="Principales"/>
            <CardFilmList titleCard="Recomendaciones para ti"/>
            <CardFilmList titleCard="Peliculas y series cómicas"/>
            <CardFilmList titleCard="Destacados de Star"/>
            <CardFilmList titleCard="Tendencias"/>
            <CardFilmList titleCard="Series dramáticas"/>
            <CardFilmList titleCard="Comedia"/>
          </section>
        </main>

        <footer className="footer">

        </footer>

      </div>
    </>
  );
}
