import {NavBar} from "@/components/atoms/nav-bar/NavBar";
import Head from "next/head";
import {AgeAdvisor} from "@/components/atoms/age-advisor/AgeAdvisor";
import {SliderItem} from "@/components/molecules/slider-item/SliderItem";
import {Slider} from "@/components/molecules/slider/Slider";


export default function Home() {
  return (
    <>
      <Head>
        <title>Disney Plus Clone</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="shortcut icon"
              href="https://static-assets.bamgrid.com/product/disneyplus/favicons/favicon-aurora.9c40657cf520f9cfcf49dbb4f316aa7c.ico"/>
      </Head>
      <div className="main-container">

        <header className="header">
          <NavBar/>
        </header>

        <main className="principal-main">
          <section>
            <AgeAdvisor>
              10
            </AgeAdvisor>

            <SliderItem>

            </SliderItem>

            <Slider></Slider>

          </section>
        </main>

        <footer>

        </footer>

      </div>
    </>
  );
}
